packageName=sqbase
appName=SQBase
appTitle=SQBase
productEclipseId=org.jkiss.sqbase.core.appstore
productModifier=ce
productType=community
productName=SQBase CE
productBrandText=Universal Database Manager
productDescription=Universal Database Manager and SQL Client
productTrademark=SQBase is a trademark of SQBase Corp
productCopyright=SQBase Corp
productEmail=support@sqbase.com
productCompany=SQBase Corp
productWebSite=https://sqbase.io/
productBundleId=org.jkiss.sqbase.core.appstore
