/*
 * SQBase - Universal Database Manager
 * Copyright (C) 2010-2026 SQBase Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jkiss.sqbase.model.sql.generator.resultset;

import org.jkiss.code.NotNull;
import org.jkiss.sqbase.DBException;
import org.jkiss.sqbase.model.DBPEvaluationContext;
import org.jkiss.sqbase.model.DBUtils;
import org.jkiss.sqbase.model.data.DBDAttributeBinding;
import org.jkiss.sqbase.model.data.DBDResultSetDataProvider;
import org.jkiss.sqbase.model.data.DBDValueRow;
import org.jkiss.sqbase.model.runtime.DBRProgressMonitor;
import org.jkiss.sqbase.model.struct.DBSAttributeBase;

import java.util.Collection;

public class SQLGeneratorInsertFromData extends SQLGeneratorResultSet {

    @Override
    public boolean isInsertOption() {
        return true;
    }

    @Override
    public boolean isDMLOption() {
        return true;
    }

    @Override
    protected void generateSQL(
        @NotNull DBRProgressMonitor monitor,
        @NotNull StringBuilder sql,
        @NotNull DBDResultSetDataProvider dataProvider
    ) throws DBException {
        for (DBDValueRow firstRow : dataProvider.getSelectedRows()) {
            Collection<? extends DBSAttributeBase> allAttributes = getAllAttributes(monitor, dataProvider);
            sql.append("INSERT INTO ").append(getEntityName(dataProvider.getSingleSource()));
            sql.append(getLineSeparator()).append("(");
            boolean hasAttr = false;
            for (DBSAttributeBase attr : allAttributes) {
                if (DBUtils.isPseudoAttribute(attr) || DBUtils.isHiddenObject(attr)) {
                    continue;
                }
                if (isExcludeAutoGeneratedColumn() && attr.isAutoGenerated()) {
                    continue;
                }
                if (hasAttr) sql.append(", ");
                sql.append(DBUtils.getObjectFullName(attr, DBPEvaluationContext.DML));
                hasAttr = true;
            }
            sql.append(")").append(getLineSeparator()).append("VALUES(");
            hasAttr = false;
            for (DBSAttributeBase attr : allAttributes) {
                if (DBUtils.isPseudoAttribute(attr) || DBUtils.isHiddenObject(attr)) {
                    continue;
                }
                if (isExcludeAutoGeneratedColumn() && attr.isAutoGenerated()) {
                    continue;
                }
                if (hasAttr) sql.append(", ");
                DBDAttributeBinding binding = DBUtils.findBinding(dataProvider.getAttributes(), attr);
                if (binding == null) {
                    appendDefaultValue(sql, attr);
                } else {
                    appendAttributeValue(dataProvider, sql, binding, firstRow, false);
                }
                hasAttr = true;
            }
            sql.append(");\n");
        }
    }
}
